version: 2

updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"

    commit-message:
      prefix: "chore"
      include: "scope"

    open-pull-requests-limit: 1

    groups:
      all-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"

    commit-message:
      prefix: "chore"
      include: "scope"

    open-pull-requests-limit: 1

    groups:
      all-actions:
        patterns:
          - "*"
