# SPDX-FileCopyrightText: 2020 Free Software Foundation Europe e.V.
# SPDX-License-Identifier: CC0-1.0
repos:
- repo: https://github.com/fsfe/reuse-tool
  rev: v6.2.0
  hooks:
  - id: reuse-lint-file

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.15.12
  hooks:
  - id: ruff-check  # linter
    args: [--fix]
  - id: ruff-format  # formatter
