docs_dir: docs
site_name: openfoodfacts-python
site_url: https://openfoodfacts.github.io/openfoodfacts-python
edit_uri: edit/develop/docs/
site_dir: gh_pages

nav:
  - Home: 'index.md'
  - Usage: 'usage.md'
  - "Handle taxonomies": 'handle_taxonomies.md'

theme:
  name: material
  features:
    - content.action.edit
  logo: https://static.openfoodfacts.org/images/logos/off-logo-horizontal-light.svg
  favicon: https://static.openfoodfacts.org/images/logos/off-logo-favicon-light.png
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
