docs_dir: docs
site_name: openfoodfacts-python
site_url: https://openfoodfacts.github.io/openfoodfacts-python
edit_uri: edit/develop/docs/
site_dir: gh_pages

nav:
  - Home: 'index.md'
  - Usage: 'usage.md'
  - "Handle taxonomies": 'handle_taxonomies.md'

theme:
  name: material
  features:
    - content.action.edit
