facets = [
    'additives',
    'allergens',
    'brands',
    'categories',
    'countries',
    'entry_dates',
    'ingredients',
    'languages',
    'packagings',
    'packaging_codes',
    'purchase_places',
    'stores',
    'traces',
    'states',
]
