name: '💥 Auto-Label Merge Conflicts on PRs'
on:
  push:
    branches:
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
jobs:
  triage:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'openfoodfacts'
    steps:
      - name: Check if PRs are dirty
        uses: eps1lon/actions-label-merge-conflict@v3
        with:
          dirtyLabel: "💥 Merge Conflicts"
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
